# Generated by Django 5.0 on 2023-12-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_chefs_insta_alter_chefs_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCanteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('dateofstart', models.DateField(null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
