# Generated by Django 5.0 on 2023-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_aboutcanteen'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Sweets', 'Sweets'), ('Toasts', 'Toasts'), ('Drinks', 'Drinks')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
