# Generated by Django 5.0 on 2023-12-22 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_menu_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutCanteen',
            new_name='PageAbout',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='Products',
        ),
        migrations.RenameIndex(
            model_name='products',
            new_name='products_pr_publish_da9952_idx',
            old_name='products_me_publish_eadede_idx',
        ),
    ]
