# Generated by Django 5.0 on 2023-12-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_chefs_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chefs'),
        ),
    ]
